services:
  backend:
    volumes:
      - ./back:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front.dev
    ports:
      - '5173:5173'
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
